### ISSUE TITLE
"npm run messages" should be able to differentiate between guest difficulties and collabs

### ISSUE THREAD

**Issue by huuishuu** [cl8n/project-loved#56]
![](https://i.imgur.com/8W0CDUM.png)

If there are multiple mappers assigned to a map that only has 1 difficulty, the script should write `Your collab map of [map name here] is going to be up for voting in [Month]'s round of Project Loved."` or something to that effect. Seems like it causes a bit of confusion when it's written like it's a guest difficulty.

_p.s. DigitalHypno suggested this:_

![](https://i.imgur.com/wugb9zV.png)

**Comment by cl8n** [comment]
I can make a special case for 1 difficulty multiple mappers but I have no way to apply this to any other instance of collabs in sets, since we don't track per-difficulty creators.

**Comment by huuishuu** [comment]
Yeah, the issue was specifically for 1 difficulty multi-mapper sets so that'd be totally fine. A way to circumvent the other ones would be to change the message to say "Your guest/collab difficulty" instead, just throwing out an idea.
