### ISSUE TITLE
Banner generator should line-break on long titles

### ISSUE THREAD

**Issue by huuishuu** [cl8n/project-loved#59]
2nd time this situation has cropped up where a song title is too long for the banner to generate the title properly. First happened with [this map](https://osu.ppy.sh/beatmapsets/1296788) and now happening again with [this map](https://osu.ppy.sh/beatmapsets/1493146). Ain't it funny how it's a different remix of the same song?

Either way, I don't think any of the news folk should be forced to arbitrarily change a song's title just for the sake of fitting the title on the banner. Just seems silly imho.

Pretty sure this situation can and probably will crop up again in the future so might as well just do something about it.

**Comment by cl8n** [comment]
closing per #osu-loved earlier
